name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push reservations service
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/reservations:latest ./reservations
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/reservations:latest

    - name: Build and push billing service
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/billing:latest ./billing
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/billing:latest

    - name: Build and push products service
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/products:latest ./products
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/products:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r ./ ec2-18-221-219-25.us-east-2.compute.amazonaws.com:/home/ec2-user/microservices

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-18-221-219-25.us-east-2.compute.amazonaws.com << 'EOF'
        cd /home/ec2-user/microservices
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/reservations:latest
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/billing:latest
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/products:latest
        docker-compose down
        docker-compose up -d --build
        EOF
